### ISSUE TITLE
Change name for title

### ISSUE THREAD

**Issue by mxdavis** [learn-co-students/rails-blog-nested-forms-v-000#501]
class User < ActiveRecord::Base
    has_many :posts
    accepts_nested_attributes_for :posts, reject_if: proc { |attributes| attributes['title'].blank? }
  end

Should have 'name' instead of 'title'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
